### ISSUE TITLE
Duply execution exit status masked

### ISSUE THREAD

**Issue by curiositycasualty** [datacoda/chef-duply#14]
Can't believe I didn't notice this before:
https://github.com/datacoda/chef-duply/blob/9411e02d0f24593b779c76aa59020e0da9b04be7/providers/default.rb#L64

Means that the last exit status chef will consider for the `execute`'s command is `sleep`'s; which will always be `0`.

**Comment by datacoda** [comment]
Ick.  That's a good point.

**Comment by curiositycasualty** [comment]
Closing own stale issues.
